services:
  app:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    command: ./scripts/docker/start.sh
    environment:
      - BROWSERLESS_API_KEY=${BROWSERLESS_API_KEY}
      - LIGHTPANDA_ENDPOINT=ws://lightpanda:9222
    entrypoint: /bin/sh
    ports:
      - "8082:8080"

  lightpanda:
    image: lightpanda/browser:0.2.9
    restart: unless-stopped
    ports:
      - "9222:9222"
