import pytest
import pytest_httpserver.httpserver as httpserver

import app.crawlers.http_client as http_client

pytestmark = pytest.mark.anyio


async def test_http_client_creation(httpserver: httpserver.HTTPServer):
    httpserver.expect_request("/test").respond_with_data("OK")
    async with http_client.create_client() as client:
        response = await client.get(httpserver.url_for("/test"))
        assert response.status_code == 200

    # Verify that headers from browserforge are applied
    assert len(httpserver.log) > 0
    request, _ = httpserver.log[0]
    headers = request.headers

    # Common headers generated by browserforge/HeaderGenerator
    assert "User-Agent" in headers
    assert "Accept" in headers
    assert "Accept-Language" in headers
    # Check for client hints which are typical for modern chrome impersonation
    assert any(key.lower().startswith("sec-ch-ua") for key in headers.keys())
